package com.example.weatherapp.repository

import androidx.compose.runtime.mutableStateListOf

val _cityList = mutableStateListOf(
    "Москва", "Санкт-Петербург", "Севастополь",
    "Майкоп", "Горно-Алтайск", "Уфа", "Улан-Удэ", "Махачкала", "Магас",
    "Нальчик", "Элиста", "Черкесск", "Петрозаводск", "Сыктывкар", "Йошкар-Ола",
    "Саранск", "Якутск", "Владикавказ", "Казань", "Кызыл", "Ижевск",
    "Абакан", "Грозный", "Чебоксары", "Барнаул", "Краснодар", "Красноярск",
    "Пермь", "Владивосток", "Ставрополь", "Хабаровск", "Благовещенск",
    "Архангельск", "Астрахань", "Белгород", "Брянск", "Владимир", "Волгоград",
    "Вологда", "Воронеж", "Иваново", "Иркутск", "Калининград", "Калуга",
    "Кемерово", "Киров", "Кострома", "Курган", "Курск", "Липецк", "Магадан",
    "Мурманск", "Нижний Новгород", "Великий Новгород", "Новосибирск", "Омск",
    "Оренбург", "Орёл", "Пенза", "Псков", "Ростов-на-Дону", "Рязань",
    "Самара", "Саратов", "Южно-Сахалинск", "Екатеринбург", "Смоленск",
    "Тамбов", "Томск", "Тула", "Тюмень", "Ульяновск", "Челябинск",
    "Ярославль", "Биробиджан", "Нарьян-Мар", "Ханты-Мансийск", "Салехард"
)

val cityNameMap = mapOf(
    "Москва" to "Moscow",
    "Санкт-Петербург" to "Saint Petersburg",
    "Севастополь" to "Sevastopol",
    "Майкоп" to "Maykop",
    "Горно-Алтайск" to "Gorno-Altaysk",
    "Уфа" to "Ufa",
    "Улан-Удэ" to "Ulan-Ude",
    "Махачкала" to "Makhachkala",
    "Магас" to "Magas",
    "Нальчик" to "Nalchik",
    "Элиста" to "Elista",
    "Черкесск" to "Cherkessk",
    "Петрозаводск" to "Petrozavodsk",
    "Сыктывкар" to "Syktyvkar",
    "Йошкар-Ола" to "Yoshkar-Ola",
    "Саранск" to "Saransk",
    "Якутск" to "Yakutsk",
    "Владикавказ" to "Vladikavkaz",
    "Казань" to "Kazan",
    "Кызыл" to "Kyzyl",
    "Ижевск" to "Izhevsk",
    "Абакан" to "Abakan",
    "Грозный" to "Grozny",
    "Чебоксары" to "Cheboksary",
    "Барнаул" to "Barnaul",
    "Краснодар" to "Krasnodar",
    "Красноярск" to "Krasnoyarsk",
    "Пермь" to "Perm",
    "Владивосток" to "Vladivostok",
    "Ставрополь" to "Stavropol",
    "Хабаровск" to "Khabarovsk",
    "Благовещенск" to "Blagoveshchensk",
    "Архангельск" to "Arkhangelsk",
    "Астрахань" to "Astrakhan",
    "Белгород" to "Belgorod",
    "Брянск" to "Bryansk",
    "Владимир" to "Vladimir",
    "Волгоград" to "Volgograd",
    "Вологда" to "Vologda",
    "Воронеж" to "Voronezh",
    "Иваново" to "Ivanovo",
    "Иркутск" to "Irkutsk",
    "Калининград" to "Kaliningrad",
    "Калуга" to "Kaluga",
    "Кемерово" to "Kemerovo",
    "Киров" to "Kirov",
    "Кострома" to "Kostroma",
    "Курган" to "Kurgan",
    "Курск" to "Kursk",
    "Липецк" to "Lipetsk",
    "Магадан" to "Magadan",
    "Мурманск" to "Murmansk",
    "Нижний Новгород" to "Nizhny Novgorod",
    "Великий Новгород" to "Veliky Novgorod",
    "Новосибирск" to "Novosibirsk",
    "Омск" to "Omsk",
    "Оренбург" to "Orenburg",
    "Орёл" to "Orel",
    "Пенза" to "Penza",
    "Псков" to "Pskov",
    "Ростов-на-Дону" to "Rostov-on-Don",
    "Рязань" to "Ryazan",
    "Самара" to "Samara",
    "Саратов" to "Saratov",
    "Южно-Сахалинск" to "Yuzhno-Sakhalinsk",
    "Екатеринбург" to "Yekaterinburg",
    "Смоленск" to "Smolensk",
    "Тамбов" to "Tambov",
    "Томск" to "Tomsk",
    "Тула" to "Tula",
    "Тюмень" to "Tyumen",
    "Ульяновск" to "Ulyanovsk",
    "Челябинск" to "Chelyabinsk",
    "Ярославль" to "Yaroslavl",
    "Биробиджан" to "Birobidzhan",
    "Нарьян-Мар" to "Naryan-Mar",
    "Ханты-Мансийск" to "Khanty-Mansiysk",
    "Салехард" to "Salekhard"
)

